# Site settings
title:
header-img: img/techblogheader4.png
email: monica.hahm@sonoport.com
description: "Sonoport Tech Blog"
baseurl: ""
url: ""
twitter_username: Sonoport
github_username:  Sonoport
facebook_username:  Sonoport


# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
